### ISSUE TITLE
二维码异常

### ISSUE THREAD

**Issue by MoAccelerator** [bighammer-link/NeteaseMusci_Upgrade#2]
![image](https://user-images.githubusercontent.com/45995147/220241050-55696294-3a42-4f29-bbae-3515ed72f525.png)
![image](https://user-images.githubusercontent.com/45995147/220241080-51578228-2a08-4b82-b837-324df330860c.png)
我很想扫 但是我做不到（）

**Comment by bighammer-link** [comment]
> ![image](https://user-images.githubusercontent.com/45995147/220241050-55696294-3a42-4f29-bbae-3515ed72f525.png) ![image](https://user-images.githubusercontent.com/45995147/220241080-51578228-2a08-4b82-b837-324df330860c.png) 我很想扫 但是我做不到（）

你这是运行在本地还是在服务器上？本地的话就请将main.py中的代码第59行注释掉，将第60行取消注释。直接展示图片进行扫码。服务器上的话，我使用的qrcode在终端生成的二维码，我是在青龙面板运行的，没有问题。

**Comment by bighammer-link** [comment]
你可以在main.py43行修改二维码的尺寸来调整一下，试一试，看看可不可以。下面是参数：
![image](https://user-images.githubusercontent.com/21276183/220330507-0e233041-28db-4d5a-9737-fb8041c1355c.png)
我每天都在用，目前代码一切正常，可能是不同终端不适配，自己调整一下吧

**Comment by MoAccelerator** [comment]
> > ![image](https://user-images.githubusercontent.com/45995147/220241050-55696294-3a42-4f29-bbae-3515ed72f525.png) ![image](https://user-images.githubusercontent.com/45995147/220241080-51578228-2a08-4b82-b837-324df330860c.png) 我很想扫 但是我做不到（）
> 
> 你这是运行在本地还是在服务器上？本地的话就请将main.py中的代码第59行注释掉，将第60行取消注释。直接展示图片进行扫码。服务器上的话，我使用的qrcode在终端生成的二维码，我是在青龙面板运行的，没有问题。
![image](https://user-images.githubusercontent.com/45995147/220332297-8a6087b9-74a6-4361-bf54-eb721aa95937.png)
按照您提供的方式，已经成功了，谢谢！
![image](https://user-images.githubusercontent.com/45995147/220333061-8fc849ad-99dc-4094-97b3-bca36a9090ac.png)

**Comment by 1250602390** [comment]
![QQ截图20230315135003](https://user-images.githubusercontent.com/97163112/225218866-5b9f6ecd-0632-4892-be3b-1055ddc7879e.png)

**Comment by 1250602390** [comment]
这是怎么回事啊大佬
